[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache_path  = 'cache_forge'
optimizer = true
deny_warnings = false
solc-version = "0.8.23"

# Profile to compile all contracts and deploy scripts
[profile.deploy]
src = 'src'
test = 'script'


# Profile to run integration tests in scroll-sepolia
[profile.integration]
eth_rpc_url = 'https://sepolia-rpc.scroll.io/'
test = 'test/'